# name of workflow
name: First Workflow
# Define Trigger of worklow
# workflow_dispatch events allow user to manuallyb trigger workflow
on: workflow_dispatch
jobs:  
  # define jobs 
  first_job:
    # define runner (executable environment)
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye" 
